### ISSUE TITLE
How to send  XSD schema in `/processFields`?

### ISSUE THREAD

**Issue by codingquark** [TamasSzekeres/abbyy-client-php#6]
I add multiple images using `SubmitImageRequest`. After this, I want to call `ProcessFieldsRequest`, with XSD Schema, as allowed by the OCR API. I cannot see the option to do this in the class.

Am I missing something? Should be using a different API?

Thanks!

**Comment by TamasSzekeres** [comment]
Hi!
You can't send XSD schema and you don't need that.
You have to send an XML file in the request body describing fields be recognized and content of the resulting XML.
XSD is only for validating your XML input. 
Unfortunately the XML input is always unique, so the api-client cannot provide an easier way to generate.
Example for XML-input for '/processFields' function:
```xml
<document xmlns="http://ocrsdk.com/schema/taskDescription-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ocrsdk.com/schema/taskDescription-1.0.xsd http://ocrsdk.com/schema/taskDescription-1.0.xsd">

<fieldTemplates></fieldTemplates>

<page applyTo="0">
       <text id="name" left="51" top="126" right="240" bottom="162">
             <language>English,German</language>
             <textType>normal</textType>
             <oneTextLine>true</oneTextLine>
       </text>
</page>
</document>
```

**Comment by codingquark** [comment]
Okay!

So `$filePath` is file path to the XML template? That makes it clear.

I am generating XML files to extract fields from the images, so I suppose input will not be an issue.

Thanks!
